// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALG2VNsOxSFJ8ReWkeW0sdWQ_2QPRDHrM',
    appId: '1:796978196424:web:e8dafe2e2e500a7b71dafd',
    messagingSenderId: '796978196424',
    projectId: 'dngfreelancejobs',
    authDomain: 'dngfreelancejobs.firebaseapp.com',
    storageBucket: 'dngfreelancejobs.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB9SsedXcVdOEZUdo1TcGWNg9vhIi6c3g',
    appId: '1:796978196424:android:af324794ed7c5e2e71dafd',
    messagingSenderId: '796978196424',
    projectId: 'dngfreelancejobs',
    storageBucket: 'dngfreelancejobs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCltxnh4S1w9bWosFc3SHiu9hBAiASjssk',
    appId: '1:796978196424:ios:bb858965e912bf4f71dafd',
    messagingSenderId: '796978196424',
    projectId: 'dngfreelancejobs',
    storageBucket: 'dngfreelancejobs.appspot.com',
    iosBundleId: 'com.example.dngFreelanceJobs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCltxnh4S1w9bWosFc3SHiu9hBAiASjssk',
    appId: '1:796978196424:ios:f012c1849b7617b171dafd',
    messagingSenderId: '796978196424',
    projectId: 'dngfreelancejobs',
    storageBucket: 'dngfreelancejobs.appspot.com',
    iosBundleId: 'com.example.dngFreelanceJobs.RunnerTests',
  );
}
